name: PR Lead Time Tracking

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          pip install requests
          python lead_time.py
